config/routes.rb
Rails.application.routes.draw do

  get 'lodging_reviews/create'
  get 'lodging_reviews/edit'
  get 'lodging_reviews/update'
  get 'lodging_reviews/destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'homes#top'
  get 'homes/about', to: 'homes#about', as: :about
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :favorites
      get :lodging_favorites
      patch :withdraw
      put :withdraw
    end
  end

  resources :eateries, only: [:new, :create, :show] do
    resource :favorite, only: [:create, :destroy]
  end
  resources :reviews, only: [:create, :edit, :update, :destroy]

  resources :lodgings, only: [:new, :create, :show] do
    resource :lodging_favorite, only: [:create, :destroy]
  end
  resources :lodging_reviews, only: [:create, :edit, :update, :destroy]

  get '/search', to: 'searches#search'


  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    post 'approved/:id', to: 'dashboards#approved', as: :approved
    post 'lodging_approved/:id', to: 'lodging_dashboards#approved', as: :lodging_approved
    resources :dashboards, only: [:index, :show, :edit, :update, :destroy]
    resources :lodging_dashboards, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :destroy] do
      member do
        patch :withdraw
        put :withdraw
      end
    end
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :eateries
  has_many :lodgings
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :lodging_favorites, dependent: :destroy
  #belongs_to :admin
  has_many :lodging_reviews, dependent: :destroy

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/user_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'user_image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_valid: false)
    reset_session
    redirect_to admin_root_path
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :reject_inactive_user, only: [:create]

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to search_path, notice: "guestuserでログインしました。"
  end

  def reject_inactive_user
    return if params[:admin]

    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.valid_password?(params[:user][:password]) && !@user.is_valid
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    #@review = Review.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    flash[:notice] = "アカウント情報を変更しました。"
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_valid: false)
    reset_session
    redirect_to root_path
  end


  #def destroy
    #@user = User.find(params[:id])
    #@user.destroy
    #flash[:notice] = 'アカウント情報を削除しました。'
    #redirect_to :root
  #end

  def favorites
    @user = User.find(params[:id])
    favorites_eatery = Favorite.where(user_id: @user.id).pluck(:eatery_id)
    favorites_lodging = LodgingFavorite.where(user_id: @user.id).pluck(:lodging_id)
    @favorite_eateries = Eatery.find(favorites_eatery)
    @favorite_lodging = Lodging.find(favorites_lodging)
  end

private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.email == "guest@example.com"
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto border border-3 rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">プロフィール編集</h5>
        <div class="form-body p-4">

          <%= form_with model: @user do |f| %>
            <label for="inputName">ユーザー名</label><br>
          <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
            <label for="inputImage">プロフィール画像</label><br>
          <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %><br>

          <div class="d-flex">
          <%= link_to "戻る", user_path(current_user), class: "btn btn-block btn-outline-secondary mt-4 mr-1" %>
          <%= f.submit '更新', class: "btn btn-block btn-outline-success mt-4" %>
          </div>
          
          <% if @user == current_user %>
            <%= link_to withdraw_user_path(current_user), method: :patch, "data-confirm" => "本当に削除しますか?", class: 'text-danger' do %>
            <i class="fa-regular fa-trash-can"></i> アカウントを削除する
            <% end %>
          <% end %>

          <% end %>
        
        </div>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-9 offset-md-1 mx-auto mt-4">
    <h5>お気に入り一覧</h5>
      <table class="table">
        <tbody>

          <% @favorite_eateries.each do |f|%>
          <tr>
            <td><h5><%= link_to f.restaurant_name, eatery_path(f.id) %></h5></td>
            <td>
              <div id="show_star_eatery-<%= f.id %>"></div>
                <script>
                  $('#show_star_eatery-<%= f.id %>').empty();
                  var elem = document.querySelector('#show_star_eatery-<%= f.id %>');
                  var opt = {
                  starOn: "<%= asset_path('star-on.png') %>",
                  starOff: "<%= asset_path('star-off.png') %>",
                  starHalf: "<%= asset_path('star-half.png') %>",
                  readOnly: true,
                  score: <%= f.reviews.average(:star).to_f %>
                  };
                  raty(elem,opt);
                </script>
            </td>
            <td><%=f.address %></td>
          </tr>
          <% end %>

          <% @favorite_lodging.each do |f|%>
          <tr>
            <td><h5><%= link_to f.lodging_name, lodging_path(f.id) %></h5></td>
            <td>
              <div id="show_star_loging-<%= f.id %>"></div>
                <script>
                  $('#show_star_lodging-<%= f.id %>').empty();
                  var elem = document.querySelector('#show_star_loging-<%= f.id %>');
                  var opt = {
                  starOn: "<%= asset_path('star-on.png') %>",
                  starOff: "<%= asset_path('star-off.png') %>",
                  starHalf: "<%= asset_path('star-half.png') %>",
                  readOnly: true,
                  score: <%= f.lodging_reviews.average(:star).to_f %>
                  };
                  raty(elem,opt);
                </script>
            </td>
            <td><%=f.address %></td>
          </tr>
          <% end %>

        </tbody>
      </table>
    </div>

    <div class="col-md-2">
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5">

        <table class="table table-borderless mb-4">
          <tr>
            <th><%= image_tag @user.get_profile_image(100,100) %></th>
            <th><h3><%= @user.name %></h3>
            <% if @user.email != "guest@example.com" %>
              <%= link_to edit_user_path, class: "btn btn-outline-success btn-block mt-1 py-0" do%>
              <i class="fa-solid fa-pen"></i> プロフィール編集
              <% end %>
            <% end %>
            <%= link_to favorites_user_path(@user), class: "btn btn-outline-secondary btn-block mt-1 py-0" do %>
              <i class="fa-solid fa-heart"></i> お気に入り一覧
            <% end %>
            </th>
          </tr>
        </table>
    </div>

    <div class="col-md-3 offset-md-4">
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">

      <h5>口コミ投稿一覧</h5>
        <table class="table table-default table-striped-columns">
          <tbody>
            <% @user.reviews.each do |review| %>
              <tr>
                <td>
                  <div style="display: flex; align-items: center;">
                  <h5 class="mt-2 mr-5"><%=link_to review.eatery.restaurant_name, eatery_path(review.eatery.id) %></h5>

                  <div id="show_star-<%= review.id %>"></div>
                    <script>
                      var elem = document.querySelector('#show_star-<%= review.id %>');
                      var opt = {
                      starOn: "<%= asset_path('star-on.png') %>",
                      starOff: "<%= asset_path('star-off.png') %>",
                      readOnly: true,
                      score: <%= review.star %>
                      };
                      raty(elem,opt);
                    </script>
                </div>

                <%= review.title %></br>
                <%= review.body %></br>

                <% review.images.each do |image| %>
                <%= image_tag image, class: "review-image image-container" %>
                <% end %>
                </td>

                <th style="display: flex; justify-content: flex-end;">
                  <span><%= link_to "編集", edit_review_path(review.id), class: "btn btn-outline-success mr-3" %></span>
                  <span><%= link_to "削除", review_path(review.id), method: :delete, "data-confirm" => "本当に消しますか?", class: "btn btn-outline-danger" %></span>
                </th>

              </tr>
            <% end %>

            <% @user.lodging_reviews.each do |review| %>
              <tr>
                <td>
                  <div style="display: flex; align-items: center;">
                  <h5 class="mt-2 mr-5"><%= link_to review.lodging.lodging_name, lodging_path(review.lodging.id)  %></h5>

                  <div id="show_star-<%= review.id %>"></div>
                    <script>
                　　    var elem = document.querySelector('#show_star-<%= review.id %>');
                　　    var opt = {
                　　    starOn: "<%= asset_path('star-on.png') %>",
                　　    starOff: "<%= asset_path('star-off.png') %>",
                　　    readOnly: true,
                　　    score: <%= review.star %>
                　　    };
                　　    raty(elem,opt);
              　　    </script>
              　</div>

                <%= review.title %></br>
                <%= review.body %></br>

                <% review.images.each do |image| %>
                  <%= image_tag image, class: "review-image image-container" %>
                <% end %>
                </td>

                <th style="display: flex; justify-content: flex-end;">
                  <span><%= link_to "編集", edit_lodging_review_path(review.id), class: "btn btn-outline-success mr-3" %></span>
                  <span><%= link_to "削除", lodging_review_path(review.id), method: :delete, "data-confirm" => "本当に消しますか?", class: "btn btn-outline-danger" %></span>
                </th>

              </tr>
            <% end %>
          </tbody>
    　　  </table>
    　</div>
  </div>

</div>