config/routes.rb
Rails.application.routes.draw do

  get 'lodging_reviews/create'
  get 'lodging_reviews/edit'
  get 'lodging_reviews/update'
  get 'lodging_reviews/destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'homes#top'
  get 'homes/about', to: 'homes#about', as: :about
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :favorites
      get :lodging_favorites
      patch :withdraw
      put :withdraw
    end
  end

  resources :eateries, only: [:new, :create, :show] do
    resource :favorite, only: [:create, :destroy]
  end
  resources :reviews, only: [:create, :edit, :update, :destroy]

  resources :lodgings, only: [:new, :create, :show] do
    resource :lodging_favorite, only: [:create, :destroy]
  end
  resources :lodging_reviews, only: [:create, :edit, :update, :destroy]

  get '/search', to: 'searches#search'


  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    post 'approved/:id', to: 'dashboards#approved', as: :approved
    post 'lodging_approved/:id', to: 'lodging_dashboards#approved', as: :lodging_approved
    resources :dashboards, only: [:index, :show, :edit, :update, :destroy]
    resources :lodging_dashboards, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :destroy] do
      member do
        patch :withdraw
        put :withdraw
      end
    end
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lodging.rb
class Lodging < ApplicationRecord

  has_one_attached :image

  belongs_to :user
  belongs_to :admin, optional: true
  has_many :lodging_reviews, dependent: :destroy
  has_many :lodging_categories, dependent: :destroy
  has_many :l_categories, through: :lodging_categories, dependent: :destroy
  has_many :lodging_favorites, dependent: :destroy

  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    image.attach(io: File.open(file_path), filename: 'udefault-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    lodging_favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Lodging.where(address: content)
    elsif method == 'partial'
      Lodging.where('address LIKE ?', '%'+content+'%')
    else
      Lodging.all
    end

  end

  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode
end

app/controllers/admin/lodging_dashboards_controller.rb
class Admin::LodgingDashboardsController < ApplicationController
 layout 'admin'
 before_action :authenticate_admin!

  def index
  @lodging = Lodging.all
  end

  def show
  @lodging = Lodging.find(params[:id])
  @categories = @lodging.l_categories
  end

  def approved
  lodging = Lodging.find(params[:id])
  lodging.update(approved: true)
  flash[:success] = "投稿が承認されました。"
  redirect_to admin_lodging_dashboards_path
  end

  def edit
  @lodging = Lodging.find(params[:id])
  end

 def update
  lodging = Lodging.find(params[:id])
  lodging.update(lodging_params)
  redirect_to admin_lodging_dashboard_path(lodging.id)
 end

 def destroy
  lodging = Lodging.find(params[:id])
  lodging.destroy
  redirect_to admin_lodging_dashboards_path
 end

 private

 def lodging_params
  params.require(:lodging).permit(:lodging_name, :address, :phone_number, :home_page, category_ids: [])
 end

end

app/helpers/admin/lodging_dashboards_helper.rb
module Admin::LodgingDashboardsHelper
end

app/views/admin/lodging_dashboards/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto border border-3 rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">編集フォーム</h5>
        <div class="form-body p-4">

          <%= form_with model: @lodging, url: admin_lodging_dashboard_path(@lodging.id) do |f| %>
            <h7>宿泊施設名</h7><br>
              <%= f.text_field :lodging_name %><br>
            <h7>住所</h7><br>
              <%= f.text_field :address %><br>
            <h7>電話番号</h7><br>
              <%= f.text_field :phone_number %><br>
            <h7>URL</h7><br>
              <%= f.text_area :home_page %><br>
            <h7><%= f.label :l_category, 'カテゴリ' %></h7><br>
              <%= f.collection_check_boxes(:l_category_ids, LCategory.all, :id, :name) do |category| %>
              <%= category.label do %>
              <%= category.check_box %>
              <%= category.text %>
              <% end %>
              <% end %>
          </br>

          <div class="d-flex">
            <%= link_to "戻る", admin_lodging_dashboard_path, class: "btn btn-block btn-outline-secondary mt-4 mr-1" %>
            <%= f.submit '保存', class: "btn btn-block btn-outline-success mt-4" %>
          </div>
          <% end %>

        </div>
    </div>
  </div>
</div>

app/views/admin/lodging_dashboards/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4">
      <h2>宿泊施設の申請履歴一覧</h2>

        <table class="table">
        　<thead class= "table-info">
            <tr>
              <th>宿泊施設名</th>
              <th>申請者</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <tbody>
            <% @lodging.each do |lodging| %>
              <tr>
                <td><%= link_to lodging.lodging_name, admin_lodging_dashboard_path(lodging.id) %></td>
                <td>
                  <% if lodging.user %>
                  <%= link_to lodging.user.name, user_path(lodging.user_id) %>
                  <% else %>
                  <%= "削除済ユーザー" %>
                  <% end %>
                </td>
                <td><%= lodging.approved ?  "承認済み" : "未承認" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

    </div>
  </div>
</div>

app/views/admin/lodging_dashboards/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mt-4">

      <% unless @lodging.approved %>
        <%= button_to "投稿を承認する", admin_lodging_approved_path(@lodging.id), method: :post, class: "btn btn-outline-secondary" %>
      <% end %>

      <table class="table mt-4">
        <tr>
          <th>店舗名</th> <td><%= @lodging.lodging_name %></td>
        </tr>
        <tr>
          <th>住所</th> <td><%= @lodging.address %></td>
        </tr>
        <tr>
          <th>電話番号</th> <td><%= @lodging.phone_number %></td>
        </tr>
        <tr>
          <th>URL</th> <td><%= @lodging.home_page %></td>
        </tr>
        <tr>
          <th>画像</th> <td><%= image_tag @lodging.image, style: "width: 100px; height: 100px" %></td>
        </tr>
        <tr>
          <th>その他</th>
          <td>
            <% @categories.each do |category| %>
            <%= category.name %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    <div class="col-md-4">
    </div>
  </div>


  <div class="row">
    <div class="col-md-4 mt-4">
      <div class="d-flex">
        <%= link_to "編集", edit_admin_lodging_dashboard_path(@lodging.id), class: "btn btn-outline-success d-inline-block w-50 mb-4 mr-1" %>
        <%= link_to "削除", admin_lodging_dashboard_path(@lodging.id), method: :delete, "data-confirm" => "本当に消しますか?", class: "btn btn-outline-danger d-inline-block w-50 mb-4" %>
      </div>
    </div>
    <div class="col-md-8">
    </div>
  </div>
</div>