config/routes.rb
Rails.application.routes.draw do

  get 'lodging_reviews/create'
  get 'lodging_reviews/edit'
  get 'lodging_reviews/update'
  get 'lodging_reviews/destroy'
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'homes#top'
  get 'homes/about', to: 'homes#about', as: :about
  resources :users, only: [:show, :edit, :update, :destroy] do
    member do
      get :favorites
      get :lodging_favorites
      patch :withdraw
      put :withdraw
    end
  end

  resources :eateries, only: [:new, :create, :show] do
    resource :favorite, only: [:create, :destroy]
  end
  resources :reviews, only: [:create, :edit, :update, :destroy]

  resources :lodgings, only: [:new, :create, :show] do
    resource :lodging_favorite, only: [:create, :destroy]
  end
  resources :lodging_reviews, only: [:create, :edit, :update, :destroy]

  get '/search', to: 'searches#search'


  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    root to: 'homes#top'
    post 'approved/:id', to: 'dashboards#approved', as: :approved
    post 'lodging_approved/:id', to: 'lodging_dashboards#approved', as: :lodging_approved
    resources :dashboards, only: [:index, :show, :edit, :update, :destroy]
    resources :lodging_dashboards, only: [:index, :show, :edit, :update, :destroy]
    resources :users, only: [:index, :destroy] do
      member do
        patch :withdraw
        put :withdraw
      end
    end
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :eateries, dependent: :destroy
  has_many :lodgings, dependent: :destroy
  #has_many :users, dependent: :destroy

  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    image.attach(io: File.open(file_path), filename: 'udefault-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :eatery_categories
  has_many :eateries, through: :eatery_categories
  has_many :initial_categories
end

app/models/eatery.rb
class Eatery < ApplicationRecord
  
  has_one_attached :image
  belongs_to :user
  #belongs_to :admin, optional: true
  has_many :reviews, dependent: :destroy
  has_many :eatery_categories, dependent: :destroy
  has_many :categories, through: :eatery_categories, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    image.attach(io: File.open(file_path), filename: 'udefault-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Eatery.where(address: content)
    elsif method == 'partial'
      Eatery.where('address LIKE ?', '%' + content + '%')
    else
      Eatery.all
    end
  end

  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode
end

app/models/eatery_bookmark.rb
class EateryBookmark < ApplicationRecord
  belongs_to :user
  belongs_to :eatery
  
  validates :user_id, uniqueness: { scope: :eatery_id }
end

app/models/eatery_category.rb
class EateryCategory < ApplicationRecord
  belongs_to :eatery
  belongs_to :category
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :eatery

  validates :user_id, uniqueness: {scope: :eatery_id}
end

app/models/initial_category.rb
class InitialCategory < ApplicationRecord
  belongs_to :category

end

app/models/l_category.rb
class LCategory < ApplicationRecord
  has_many :lodging_categories​
  has_many :lodgings, through: :lodging_categories
  has_many :initial_category_lodgings
end

app/models/l_catetory.rb
class LCatetory < ApplicationRecord
  has_many :lodging_categories​
  has_many :lodging, through: :lodging_categories​
  has_many :initial_category_lodgings
end

app/models/lodging.rb
class Lodging < ApplicationRecord

  has_one_attached :image

  belongs_to :user
  belongs_to :admin, optional: true
  has_many :lodging_reviews, dependent: :destroy
  has_many :lodging_categories, dependent: :destroy
  has_many :l_categories, through: :lodging_categories, dependent: :destroy
  has_many :lodging_favorites, dependent: :destroy

  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    image.attach(io: File.open(file_path), filename: 'udefault-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    lodging_favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Lodging.where(address: content)
    elsif method == 'partial'
      Lodging.where('address LIKE ?', '%'+content+'%')
    else
      Lodging.all
    end

  end

  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode
end

app/models/lodging_category.rb
class LodgingCategory < ApplicationRecord
  belongs_to :lodging
  belongs_to :l_category
end

app/models/lodging_favorite.rb
class LodgingFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :lodging

  validates :user_id, uniqueness: {scope: :lodging_id}
end

app/models/lodging_review.rb
class LodgingReview < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  belongs_to :lodging
  
  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    image.attach(io: File.open(file_path), filename: 'udefault-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/review.rb
class Review < ApplicationRecord
  has_many_attached :images
  belongs_to :user
  belongs_to :eatery
  #belongs_to :lodging

  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/default-image.jpg')
    image.attach(io: File.open(file_path), filename: 'udefault-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :eateries
  has_many :lodgings
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :lodging_favorites, dependent: :destroy
  #belongs_to :admin
  has_many :lodging_reviews, dependent: :destroy

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/user_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'user_image.jpg', content_type: 'image/jpeg')
  end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end



end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

	def search
		@model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'eatery'
			@eatery_records = Eatery.where(approved: true).search_for(@content, @method)
		elsif @model == 'lodging'
			@lodging_records = Lodging.search_for(@content, @method)
		else
			@eatery_records = Eatery.where(approved: true)
			@lodging_records = Lodging.where(approved: true)
		end
	end

end

app/helpers/eateries_helper.rb
module EateriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lodgings_helper.rb
module LodgingsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/searches/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mx-auto mt-4">
      <div class="input-group">
        <% if user_signed_in? %>
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <div class="d-flex">
              <%= f.text_field :content, class: "form-control mr-1", style: "width: 300px;", placeholder: "住所を入力" %>
              <%= f.select :model, options_for_select({ "飲食店" => "eatery", "宿泊施設" => "lodging" }), { }, { class: 'form-control mr-1', style: "width: 130px;" } %>
              <%= f.select :method, options_for_select({ "完全一致" => "perfect", "部分一致" => "partial" }), { }, { class: 'form-control mr-1', style: "width: 150px;" } %>
              <%= f.button class: "btn btn-outline-secondary", style: "min-width: 45px;" do %>
                <i class="fa-solid fa-magnifying-glass"></i>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 mt-4 mb-4">
      <div class="card-container d-flex">

        <% if @model == 'eatery' %>
          <% @eatery_records.each do |eatery| %>
            <div class="card">
              <% if eatery.image.attached? %>
                <%= image_tag eatery.image.variant(gravity: :center, resize:"640x640^", crop:"640x640+0+0").processed, class:"card-img-top", alt:"Image" %>
              <% else %>
                <%= image_tag "default-image.jpg", class:"card-img-top", alt:"Image" %>
              <% end %>
                <div class="card-body">
                  <div class="card-title">
                    <h5><%= link_to eatery.restaurant_name, eatery_path(eatery.id) %></h5>
                  </div>
                  <div class="card-text">
                    <div id="show_star_eatery-<%= eatery.id %>"></div>
                      <script>
                        $('#show_star_eatery-<%= eatery.id %>').empty();
                        var elem = document.querySelector('#show_star_eatery-<%= eatery.id %>');
                        var opt = {
                        starOn: "<%= asset_path('star-on.png') %>",
                        starOff: "<%= asset_path('star-off.png') %>",
                        starHalf: "<%= asset_path('star-half.png') %>",
                        readOnly: true,
                        score: <%= eatery.reviews.average(:star).to_f %>
                        };
                        raty(elem,opt);
                      </script>
                      </br>
                      <i class="fa-solid fa-location-dot"></i> <%= eatery.address %>
                  </div>
                </div>
            </div>
          <% end %>

        <% elsif @model == 'lodging' %>
          <% @lodging_records.each do |lodging| %>
            <div class="card">
              <% if lodging.image.attached? %>
                <%= image_tag lodging.image.variant(gravity: :center, resize:"640x640^", crop:"640x640+0+0").processed, class:"card-img-top", alt:"Image" %>
              <% else %>
                <%= image_tag "default-image.jpg", class:"card-img-top", alt:"Image" %>
              <% end %>
                <div class="card-body">
                  <div class="card-title">
                    <h5><%= link_to lodging.lodging_name, lodging_path(lodging.id) %></h5>
                  </div>
                  <div class="card-text">
                    <div id="show_star_loging-<%= lodging.id %>"></div>
                      <script>
                        $('#show_star_lodging-<%= lodging.id %>').empty();
                        var elem = document.querySelector('#show_star_loging-<%= lodging.id %>');
                        var opt = {
                        starOn: "<%= asset_path('star-on.png') %>",
                        starOff: "<%= asset_path('star-off.png') %>",
                        starHalf: "<%= asset_path('star-half.png') %>",
                        readOnly: true,
                        score: <%= lodging.lodging_reviews.average(:star).to_f %>
                        };
                        raty(elem,opt);
                      </script>
                      </br>
                      <i class="fa-solid fa-location-dot"></i> <%= lodging.address %>
                  </div>
                </div>
            </div>
          <% end %>

        <% else %>
          <% @eatery_records.each do |eatery| %>
            <div class="card">
              <% if eatery.image.attached? %>
                <%= image_tag eatery.image.variant(gravity: :center, resize:"640x640^", crop:"640x640+0+0").processed, class:"card-img-top", alt:"Image" %>
              <% else %>
                <%= image_tag "default-image.jpg", class:"card-img-top", alt:"Image" %>
              <% end %>
                <div class="card-body">
                  <div class="card-title">
                    <h5><%= link_to eatery.restaurant_name, eatery_path(eatery.id) %></h5>
                  </div>
                  <div class="card-text">
                    <div id="show_star_eatery-<%= eatery.id %>"></div>
                      <script>
                        $('#show_star_eatery-<%= eatery.id %>').empty();
                        var elem = document.querySelector('#show_star_eatery-<%= eatery.id %>');
                        var opt = {
                        starOn: "<%= asset_path('star-on.png') %>",
                        starOff: "<%= asset_path('star-off.png') %>",
                        starHalf: "<%= asset_path('star-half.png') %>",
                        readOnly: true,
                        score: <%= eatery.reviews.average(:star).to_f %>
                        };
                        raty(elem,opt);
                      </script>
                      </br>
                      <i class="fa-solid fa-location-dot"></i> <%= eatery.address %>
                  </div>
                </div>
            </div>
          <% end %>

          <% @lodging_records.each do |lodging| %>
            <div class="card">
              <% if lodging.image.attached? %>
                <%= image_tag lodging.image.variant(gravity: :center, resize:"640x640^", crop:"640x640+0+0").processed, class:"card-img-top", alt:"Image" %>
              <% else %>
                <%= image_tag "default-image.jpg", class:"card-img-top", alt:"Image" %>
              <% end %>
                <div class="card-body">
                  <div class="card-title">
                    <h5><%= link_to lodging.lodging_name, lodging_path(lodging.id) %></h5>
                  </div>
                  <div class="card-text">
                    <div id="show_star_lodging-<%= lodging.id %>"></div>
                      <script>
                        $('#show_star_lodging-<%= lodging.id %>').empty();
                        var elem = document.querySelector('#show_star_lodging-<%= lodging.id %>');
                        var opt = {
                        starOn: "<%= asset_path('star-on.png') %>",
                        starOff: "<%= asset_path('star-off.png') %>",
                        starHalf: "<%= asset_path('star-half.png') %>",
                        readOnly: true,
                        score: <%= lodging.lodging_reviews.average(:star).to_f %>
                        };
                        raty(elem,opt);
                      </script>
                      </br>
                      <i class="fa-solid fa-location-dot"></i> <%= lodging.address %>
                  </div>
                </div>
            </div>
          <% end %>

        <% end %>
      </div>
    </div>

  </div>
</div>